# -*- coding: utf-8 -*-
"""FinalProject502.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSjMvWKUsNVeUO0UqG0sFDFnqR1QhCYd
"""

# Ralchukwu Mogbogu

# import data
placement <- read.csv("Placement_Data_Full_Class.csv")

# data preview
head(placement)

str(placement)

# data cleaning
# step 1: convert all char to factor
placement$gender <- factor(placement$gender)
placement$ssc_b <- factor(placement$ssc_b)
placement$hsc_b <- factor(placement$hsc_b)
placement$hsc_s <- factor(placement$hsc_s)
placement$degree_t <- factor(placement$degree_t)
placement$workex <- factor(placement$workex)
placement$specialisation <- factor(placement$specialisation)
placement$status <- factor(placement$status)
# step 2: delete sl_no
placement <- placement[,-c(1)]
# step 3: convert placement status to numerical variable
temp.map <- c("Placed"=1, "Not Placed"=0)
placement$status_num <- temp.map[as.character(placement$status)]

str(placement)
summary(placement)

#step 4: check if dependent variable is normal, do log transformation if necessary
hist(placement$salary, breaks=20)
hist(log(placement$salary),breaks=20)
hist(sqrt(placement$salary), breaks=20)

qqnorm(placement$salary)
qqline(placement$salary)
qqnorm(log(placement$salary))
qqline(log(placement$salary))
qqnorm(sqrt(placement$salary))
qqline(sqrt(placement$salary))

placement$logsalary = log(placement$salary)

# Single variable inference
# correlation plot
install.packages('corrplot')
library(corrplot)
correlations <- cor(placement[, -c(1,3,5,6,8,9,11,13)], use="pairwise.complete.obs")
corrplot(correlations)

correlations

# we want to use the inference function from this file to do t-test
download.file("http://www.openintro.org/stat/data/atheism.RData", destfile = "atheism.RData")
load("atheism.RData")

# categorical variable inference
# Does different gender have different placement percentage?
# The two below look equivalent
inference(y=placement$status, x = placement$gender,
                      est = c("proportion"),
                      success = "Placed",
                      alternative = c("twosided"),
                      type = c("ht"), method = c("theoretical"))


inference(y=placement$status_num, x = placement$gender,
                      est = c("mean"),
                      null = 0,
                      alternative = c("twosided"),
                      type = c("ht"), method = c("theoretical"))

# categorical variable inference
# Does different gender have different salary level
# t-test assume y follows normal distribution, it's better to test logsalary instead of salary
inference(y=placement$logsalary, x = placement$gender,
                      est = c("mean"),
                      null = 0,
                      alternative = c("twosided"),
                      type = c("ht"), method = c("theoretical"))

# categorical variable inference
# Does different higher secondary education level have the same placement percentage?
# When categorical variables have more than 2 levels, we need to use ANOVA instead of t-test
res_aov <- aov(status_num ~ hsc_s,
  data = placement
)

summary(res_aov)

# categorical variable inference
# Does different higher secondary education level have the same salary?
# When categorical variables have more than 2 levels, we need to use ANOVA instead of t-test

boxplot(placement$logsalary ~ placement$hsc_s)

res_aov <- aov(logsalary ~ hsc_s,
  data = placement
)

summary(res_aov)

# categorical variable inference
# Does different mbs specialisation have different salary level
# t-test assume y follows normal distribution, it's better to test logsalary instead of salary
inference(y=placement$logsalary, x = placement$specialisation,
                      est = c("mean"),
                      null = 0,
                      alternative = c("twosided"),
                      type = c("ht"), method = c("theoretical"))
                      
##post hoc
res_posthoc<-TukeyHSD(res_aov)
res_posthoc

plot(res_posthoc, las = 1, col = "blue")

# Regression
# Linear regression: predict salary level
# In general it's a bad idea as residual doesn't have constant variance. R2 is low as well

bad_forward_model = lm(salary ~ 1, data=placement)
bad_forward_model = step(bad_forward_model, direction='forward', scope=(~ gender + ssc_p + ssc_b + hsc_p + hsc_b + hsc_s + degree_p + degree_t + workex + etest_p + specialisation + mba_p), trace=1)
summary(bad_forward_model)

plot(bad_forward_model$fitted.values, bad_forward_model$residuals)
qqnorm(bad_forward_model$residuals)
plot(bad_forward_model$fitted.values, model.frame(bad_forward_model)$salary)

# Regression
# Linear regression: predict logsalary level, much better

backward_model <- lm(logsalary ~ gender + ssc_p + ssc_b + hsc_p + hsc_b + hsc_s + degree_p + degree_t + workex + etest_p + specialisation + mba_p, data = placement)

# Backward stepwise regression
backward_model <- step(backward_model, direction = "backward", trace = 1)
summary(backward_model)

# forward model and backward model happen to have the same result
forward_model = lm(logsalary ~ 1, data=placement)

# forward stepwise regression
forward_model = step(forward_model, direction='forward', scope=(~ gender + ssc_p + ssc_b + hsc_p + hsc_b + hsc_s + degree_p + degree_t + workex + etest_p + specialisation + mba_p), trace=1)
summary(forward_model)

# residual diagnostic looks much better
plot(forward_model$fitted.values, forward_model$residuals)
qqnorm(forward_model$residuals)
qqline(forward_model$residuals)
plot(forward_model$fitted.values, model.frame(forward_model)$logsalary)

# Regression
# Logit regression: predict placement probability
# It's great to see workex and high school performance helps placement but not salary. It's a good story.

logit_forward_model = glm(status_num ~ 1, data=placement, family=binomial)
logit_forward_model = step(logit_forward_model, direction='forward', scope=(~ gender + ssc_p + ssc_b + hsc_p + hsc_b + hsc_s + degree_p + degree_t + workex + etest_p + specialisation + mba_p), trace=1)

summary(logit_forward_model)
